security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                remember_me:  true
                csrf_provider: form.csrf_provider
                default_target_path: /dashboard
                failure_path: /erreur
                use_referer : true
            remember_me:
                key: %secret%
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/showBrowsers, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/showOS, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/showDevice, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/showForfait, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/useragent, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, role: ROLE_ADMIN }



    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN