users:
  type: rest
  resource: Time\TrackerBundle\Controller\UsersController

users:
  type: rest
  resource: Time\TrackerBundle\Controller\AgentController

user:
    type: rest
    resource: Time\TrackerBundle\Controller\UserController


information_show:
  pattern:  /{id}/show
  defaults: { _controller: TimeTrackerBundle:User:show, _format: json }
  requirements: { id: \d+ }
  methods:   [Get]

information_edit:
  pattern:  /{id}/edit
  resource: Time\TrackerBundle\Controller\UserController
  requirements: { id: \d+ }
  methods:   [Get]

regex_show:
  pattern:  /{id}/show
  defaults: { _controller: TimeTrackerBundle:Regex:show, _format: json }
  requirements: { id: \d+ }
  methods:   [Get]

regex_edit:
  pattern:  /{id}/edit
  resource: Time\TrackerBundle\Controller\RegexController
  requirements: { id: \d+ }
  methods:   [Get]



affiche_os:
  pattern:  /os
  resource: Time\TrackerBundle\Controller\AfficheController
  methods:   [Get]

affiche_navigateur:
  pattern:  /navigateur
  resource: Time\TrackerBundle\Controller\AfficheController
  methods:   [Get]


profile_home:
  pattern:  /home
  resource: Time\TrackerBundle\Controller\PageController
  methods:   [Get]

firefox_firefox:
  pattern:  /firefox
  resource: Time\TrackerBundle\Controller\FirefoxController
  methods:   [Get]


recuper:
  type: rest
  resource: Time\TrackerBundle\Controller\RecupererController

envoyertoken:
  type: rest
  resource: Time\TrackerBundle\Controller\EnvoyerTokenController
