users:
  type: rest
  resource: Time\TrackerBundle\Controller\UsersController

users:
  type: rest
  resource: Time\TrackerBundle\Controller\AgentController

userss:
  type: rest
  resource: Time\TrackerBundle\Controller\AfficheController

usersss:
  type: rest
  resource: Time\TrackerBundle\Controller\EnvoyerTokenController

user:
    type: rest
    resource: Time\TrackerBundle\Controller\UserController


affiche_showOS:
  pattern:  /showOS
  defaults: { _controller: TimeTrackerBundle:Affiche:os, _format: json }
  requirements: { id: \d+ }
  methods:   [Get]

affiche_showBrowsers:
  pattern:  /showBrowsers
  defaults: { _controller: TimeTrackerBundle:Affiche:navigateur, _format: json }
  requirements: { id: \d+ }
  methods:   [Get]

affiche_showDevice:
  pattern:  /showDevice
  defaults: { _controller: TimeTrackerBundle:Affiche:device, _format: json }
  requirements: { id: \d+ }
  methods:   [Get]


information_showForfait:
  pattern:  /showForfait
  defaults: { _controller: TimeTrackerBundle:Forfait:Forfait, _format: json }
  methods:   [Get]

Save_forfait:
  pattern:  /Save_forfait/{id}
  defaults: { _controller: TimeTrackerBundle:Forfait:Save_forfait, _format: json }
  requirements: { id: \d+ }
  methods:   [Get]

forfait_choiceforfait:
  pattern:  /choiceforfait
  resource: Time\TrackerBundle\Controller\ForfaitController
  methods:   [Get]

affiche_statistique:
  pattern:  /statistique
  resource: Time\TrackerBundle\Controller\AfficheController
  methods:   [Get]

affiche_useragent:
  pattern:  /useragent
  resource: Time\TrackerBundle\Controller\AfficheController
  methods:   [Get]

profile_home:
  pattern:  /home
  resource: Time\TrackerBundle\Controller\PageController
  methods:   [Get]

erreur:
  pattern:  /erreur
  resource: Time\TrackerBundle\Controller\ErreurController
  methods:   [Get]

dashboard:
  pattern:  /dashboard
  resource: Time\TrackerBundle\Controller\DashboardController
  methods:   [Get]



recuper:
  type: rest
  resource: Time\TrackerBundle\Controller\RecupererController

envoyertoken:
  type: rest
  resource: Time\TrackerBundle\Controller\EnvoyerTokenController






regex_show:
  pattern:  /{id}/show
  defaults: { _controller: TimeTrackerBundle:Regex:show, _format: json }
  requirements: { id: \d+ }
  methods:   [Get]

regex_edit:
  pattern:  /{id}/edit
  resource: Time\TrackerBundle\Controller\RegexController
  requirements: { id: \d+ }
  methods:   [Get]



information_show:
  pattern:  /{id}/show
  defaults: { _controller: TimeTrackerBundle:User:show, _format: json }
  requirements: { id: \d+ }
  methods:   [Get]

information_edit:
  pattern:  /{id}/edit
  resource: Time\TrackerBundle\Controller\UserController
  requirements: { id: \d+ }
  methods:   [Get]

